### ISSUE TITLE
Number of decimal places for retention time in identifiers

### ISSUE THREAD

**Issue by melpetera** [workflow4metabolomics/camera#11]
It would be nice to have a similar option for retention time as it exists for mass regarding decimal places in ion identifiers. 
In other word, it would be nice to be able to choose between "M101.98T5" and "M101.98T4.9" for example. It could be similar to the existing parameter for mass in identifiers.

**Comment by lecorguille** [comment]
Crossref: https://github.com/workflow4metabolomics/xcms/issues/22

**Comment by lecorguille** [comment]
TODO:

- [x] Do as suggested by @yguitton https://github.com/workflow4metabolomics/xcms/issues/22#issuecomment-269042323

**Comment by lecorguille** [comment]
Available within the dev galaxy instance

**Comment by melpetera** [comment]
Ok for me.

**Comment by lecorguille** [comment]
- [X]  validated by @melpetera 
- [ ]  validated by @yguitton 
- [ ]  validated by @jfrancoismartin

**Comment by lecorguille** [comment]
Thanks Mélanie
