### ISSUE TITLE
New column: "namecustom"

### ISSUE THREAD

**Issue by melpetera** [workflow4metabolomics/camera#14]
This issue concerns the peak table export. 

The idea is to:
- keep default ion identifiers,
- add a "namecustom" column corresponding to what a user asks about decimal places for mass and retention time, and convertion of rt into minutes.

**Comment by lecorguille** [comment]
Available within the dev galaxy instance

**Comment by melpetera** [comment]
Ok for me!

**Comment by lecorguille** [comment]
- [X]  validated by @melpetera 
- [ ]  validated by @yguitton 
- [ ]  validated by @jfrancoismartin

**Comment by lecorguille** [comment]
Thanks Mélanie
