### ISSUE TITLE
Camera.combinexannos: sync export with xcms.group, xcms.fillpeaks and Camera.annotate

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/camera#16]
https://github.com/workflow4metabolomics/camera/issues/14

**Comment by lecorguille** [comment]
Available within the dev galaxy instance

**Comment by lecorguille** [comment]
- [x]  validated by @melpetera 
- [ ]  validated by @yguitton 
- [ ]  validated by @jfrancoismartin

**Comment by melpetera** [comment]
Is the "General used intensity value" parameter used in this module? I would say "no" but best is to ask. At least it does not change the results obtained with my test datasets. 

Ok for the other parameters: works perfectly.

**Comment by lecorguille** [comment]
Hum ... it should! I will look at that

**Comment by lecorguille** [comment]
@melpetera Hum ... [` peakList=getPeaklist(xa,intval=listArguments[["intval"]])`](https://github.com/workflow4metabolomics/camera/blob/dev/src/camera_w4m_script/lib.r#L89) ?

**Comment by melpetera** [comment]
Maybe, but the intensity values are not part of the output files. This parameter is meant to determine what "kind" of intensity should be reported. I guess you only use getPeaklist to get the "variableMetadata" part, don't you? Or do you use the intensities after that?

**Comment by lecorguille** [comment]
@melpetera Hum ... [`dataMatrix = peakList[,(make.names(colnames(peakList)) %in% c("name", make.names(sampnames(xa@xcmsSet))))]`](https://github.com/workflow4metabolomics/camera/blob/dev/src/camera_w4m_script/lib.r#L93)

**Comment by melpetera** [comment]
Ah... but there is no dataMatrix as output? Your lines are from CAMERA.annotate, not the combinexannos?

**Comment by lecorguille** [comment]
Hum ... camera.annotate generate a dataMatrix: `xset.group.retcor.group.fillPeaks.annotateDiffreport.dataMatrix.tsv`
Actually, do we speak about the same thing?

**Comment by melpetera** [comment]
This issue is about combinexannos, not CAMERA.annotate. Or am I wrong?

**Comment by lecorguille** [comment]
My bad 😭

**Comment by lecorguille** [comment]
Fix: https://github.com/workflow4metabolomics/camera/pull/29/commits/ef16b89ecc8c15d7cbab94c46337dce6ed8f268b

**Comment by melpetera** [comment]
Retested: should be ok when #25 will be ok.
(can not be tested with the last last version of CAMERA.annotate due to the "quick" name problem)

**Comment by melpetera** [comment]
Validated.

**Comment by lecorguille** [comment]
Thanks Mélanie
