### ISSUE TITLE
ZIP file with EIC.png and boxplot.png please come back....

### ISSUE THREAD

**Issue by yguitton** [workflow4metabolomics/camera#34]
Following OTRS ticket [Ticket#2017062810000119] i would like to have an option that create a zip file with with individual eic.png and boxplot.png (as it was before). I know that all eics and boxplot are in the pdfs now, be we are using an excel macro in my lab that need EIC.png  as individual files.

cheers

**Comment by yguitton** [comment]
One new demand from S. Chéreau received this morning [Ticket#2018110710000012 — Requests on XCMS.]
Hello everyone,
 
About CAMERA.annotate step,
 
1-When selecting "two or more conditions" in CAMERA.annotate would it be possible to get EIC & boxplots as png (in a zip file when downloaded) and not in a pdf file ?
2-If I'm correct EICs and boxplots are generated from uncorrected data (batch correction). Would it be possible to draw them after correction/normalisation (maybe not, as the correction is applied on peak area / height)?

Looking forward to hearing from you,
Best,
Sylvain

**Comment by yguitton** [comment]
reopen please

**Comment by lecorguille** [comment]
Should be done: https://github.com/workflow4metabolomics/camera/pull/41
@yguitton You can test that on galaxydev.
Let me know

**Comment by yguitton** [comment]
Merci

**Comment by lecorguille** [comment]
@yguitton You can test the fix on the dev

**Comment by lecorguille** [comment]
Done
