### ISSUE TITLE
Suggestion about dataMatrix output

### ISSUE THREAD

**Issue by melpetera** [workflow4metabolomics/camera#39]
Hi @lecorguille , @yguitton , @jfrancoismartin and whom is intrested in this question,

I noticed that CAMERA.annotate did not have the "NA to 0" option. I was going to ask for the addition of this parameter, but then I realised that the best solution may be something else. 

Indeed, previously CAMERA.annotate was the final mandatory step to obtain the extracted data in our workflow, so it was relevant to have the dataMatrix here as output. But now, we can have enough information to continue the workflow at the group or fillPeaks step. So in fact, what CAMERA.annotate brings us is precious information but that is only given in the variableMetadata file. 

Thus, I would say that with our new workflow it is more relevant to get the dataMatrix at the fillPeaks step, and to only focus on the variableMetadata file for CAMERA.annotate. In particular, this can help explaining that CAMERA.annotate as only 2 focus: pure CAMERA part and diffreport part. 

So what I suggest:
- no more dataMatrix as output in CAMERA.annotate
- suppression of "General used intensity value" in the "Export options" in CAMERA.annotate (not used anymore) 
- make the "Get a Peak List" mandatory in fillchrompeaks as it is the endpoint for dataMatrix. 

What do you think about it?

Mélanie

**Comment by lecorguille** [comment]
Done here: https://github.com/workflow4metabolomics/camera/pull/40
