### ISSUE TITLE
allows use of rules option in CAMERA

### ISSUE THREAD

**Issue by yguitton** [workflow4metabolomics/camera#8]
in findAdduct it is possible to use a user defined csv as ruleset for adduct annotation it would be great to have that option in CAMERA

"just" add a load csv file option in xml warper

**myrules**<-read.csv("my_extended_NEG_rules.csv")
annotateDiffreport(object, sample=NA, nSlaves=1, sigma=6, perfwhm=0.6,
  cor_eic_th=0.75, cor_exp_th = 0.75, graphMethod="hcs", pval=0.05, calcCiS=TRUE,
  calcIso=FALSE, calcCaS=FALSE, maxcharge=3, maxiso=4, minfrac=0.5,
  ppm=5, mzabs=0.015, quick=FALSE, psg_list=NULL, **rules=myrules**,
  polarity="positive", multiplier=3, max_peaks=100, intval="into",
  pval_th = NULL, fc_th = NULL, sortpval=TRUE, ...)

**Comment by lecorguille** [comment]
Thank you!
I will start the development ASAP

**Comment by lecorguille** [comment]
@yguitton can you send me a "my_extended_NEG_rules.csv". It must be an "Open source" example

**Comment by lecorguille** [comment]
@yguitton @jfrancoismartin 
You can test this new feature on galaxydev.sb-roscoff.fr
Maybe you will have to switch the the 2.1.6 version of annotate

**Comment by jfrancoismartin** [comment]
Hello. 
Thank you for this functionality. But I couln't enter a csv ruleset. I used GetData upload but my csv files doesn't appear in the box. I have the message "no csv dataset available". I think I didn't used the right way to upload the data...

**Comment by yguitton** [comment]
Testing the new option right now...

**Comment by jfrancoismartin** [comment]
Hi,
It seems that the program still uses the same default CAMERA ruleset. I tried using a very simple inhouse file with just Na and K adduct and I have the same result as with the default. Or may be I did some mistakes...

**Comment by yguitton** [comment]
Hi,

same on my side I have created a csv with [M+H]+ adduct renamed as [M+H(C13)]+ and [M+K]+ renamed as [M+K39]+. and i still have [M+H]+ and [M+K]+ in my final camera list

after some searches in the code of add-rules branch it seems that ruleset<-listargument[[ruleset]] which is not the correct way of adding rules. rulset=read.table(listargument[[]], h=T, sep=",") 

i see a lot of annotate function in the code and none of them use rules. depending on user choice all these annotate function should have rules =read.table(listargument[[]], h=T, sep=",")  or rules=NULL

**Comment by lecorguille** [comment]
Thanks for those feedback.
I will investigate on that. Have you share me some histories?

**Comment by jfrancoismartin** [comment]
share history
 http://galaxydev.sb-roscoff.fr/u/jfmartin/h/test-adduct-list-inhouse
Steps 34-35 and steps  23-22 correspond to 2 different rulesets but show the same adduct.
Good luck

**Comment by lecorguille** [comment]
Fix: @jfrancoismartin @yguitton, the ruleset file wasn't use because of a bad copy/paste in the xml command tag ... looser
Fix: indeed, @yguitton, you were right, annote take a data.frame, not a filename

So try again!

Thanks to you both for testing

**Comment by jfrancoismartin** [comment]
It works....

**Comment by jfrancoismartin** [comment]
I checked with 2 different rulesets and it works !!! Thank you for this functionality. It will help us a lot.

**Comment by lecorguille** [comment]
I'm glad to hear that @jfrancoismartin !
As soon as Yann confirm with his setup.
I merge and push to the TS

**Comment by lecorguille** [comment]
@yguitton Can you confirm that this new feature "add rules" works correctly?

Thanks

**Comment by yguitton** [comment]
Sorry I didn't managed to make it work but maybe because of my rules.csv file. still trying to understand why when uploaded from my pc. the format tsv txt or csv

**Comment by lecorguille** [comment]
https://github.com/workflow4metabolomics/camera/pull/18

**Comment by lecorguille** [comment]
Available within the dev galaxy instance

**Comment by lecorguille** [comment]
- [X]  validated by @yguitton but https://github.com/workflow4metabolomics/workflow4metabolomics/issues/11
- [X]  validated by @jfrancoismartin
